export const dataProperties = [
  {
    id: 1,
    location: "Jacuzzi Spa - Firplak",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "ba1.jpg",
    star: 4.5,
    meters: 430,
    description:
      "Un jacuzzi ergonómico con 8 potentes hidrojets y 18 microjets para masajes en las principales zonas musculares del cuerpo ",
  },
  {
    id: 2,
    location: "Hidromasaje Santorini Spa – Firplak",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    image: "ba2.jpg",
    star: 4,
    meters: 230,
    description:
      "Ergonomía, hidroterapia, cromoterapia, aeroterapia opcional, panel de control, mantenedor de temperatura ",
  },
  {
    id: 3,
    location: "Termales Santa Rosa de Cabal",
    price: 350000 ,
    bedrooms: 5,
    bathroom: 2,
    image: "ba3.jpg",
    star: 5,
    meters: 90,
    description:
      "Aguas termales, masajes, sauna, ambiente relajante ",
  },
  {
    id: 4,
    location: "Makuira Beer Spa",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "ba4.png",
    star: 4.2,
    meters: 120,
    description:
      "Baños de cerveza, masajes, ambiente relajant ",
  },
  {
    id: 5,
    location: "Mascarilla Refrescante de Cebolla y Yogur",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "facial1.jpg",
    star: 4.1,
    meters: 87,
    description:
      "Perfecta para piel grasa y propensa al acné, esta mascarilla ayuda a reducir la producción de grasa y refresca la piel. ",
  },
  {
    id: 6,
    location: "Mascarilla Nutritiva de Chocolate y Miel",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "facial2.jpg",
    star: 4.7,
    meters: 220,
    description:
      "Ideal para piel normal y mixta, esta mascarilla proporciona nutrientes esenciales y mejora la textura de la piel.",
  },
  {
    id: 7,
    location: "Mascarilla Antiedad de Ácido Hialurónico:",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "facial3.jpg",
    star: 4.5,
    meters: 430,
    description:
      "Perfecta para piel madura, esta mascarilla ayuda a reducir arrugas y líneas finas gracias a su contenido de ácido hialurónico. ",
  },
  {
    id: 8,
    location: "Mascarilla Hidratante de Aloe Vera",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "facial4.jpg",
    star: 4.5,
    meters: 330,
    description:
      "Ideal para piel seca y sensible, esta mascarilla hidrata profundamente gracias a los beneficios del aloe vera.",
  },
  {
    id: 9,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "pro1.jpg",
    star: 4.5,
    meters: 380,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 10,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "pro2.jpg",
    star: 4.1,
    meters: 270,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 11,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "pro3.jpg",
    star: 5,
    meters: 430,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 12,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "pro4.jpg",
    star: 3.9,
    meters: 76,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 13,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "spa1.jpg",
    star: 4.8,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 14,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "spa2.jpg",
    star: 4.9,
    meters: 180,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 15,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "spa3.jpg",
    star: 4.1,
    meters: 287,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
  {
    id: 16,
    location: "Cuenca, Valencia, ES",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "spa4.jpg",
    star: 4,
    meters: 290,
    description:
      "En el corazón de la encantadora ciudad de Cuenca, te presentamos una oportunidad única de adquirir un espectacular piso de 75 metros cuadrados que combina comodidad, elegancia y un entorno natural inigualable. Esta vivienda, ubicada en una zona tranquila y bien comunicada, es un refugio de paz y belleza que estamos seguros te enamorará.. . Al entrar a este acogedor hogar, te recibirá un amplio recibidor que te conducirá a un baño completo con bañera, perfecto para relajarte después de un largo día. Continuando, te adentrarás en un generoso salón comedor, que se fusiona con la cocina a través de puertas correderas. ",
  },
];
